apiVersion: v1
kind: ConfigMap
metadata:
  name: uptimatum-config
  namespace: uptimatum
data:
  DB_HOST: "postgres-postgresql-ha-pgpool.uptimatum.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "uptimatum"
  CHECK_INTERVAL: "30"
  CHECK_TIMEOUT: "10"
  PORT: "3000"

